# Generated by Django 3.2.16 on 2022-11-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_bankcurrency_merchant_usercurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcurrency',
            name='denomination',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bankcurrency',
            name='spend_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='address',
            field=models.CharField(default='Address', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='owner',
            field=models.CharField(default='Owner', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='phone',
            field=models.CharField(default='05xxxxxxx', max_length=100),
        ),
        migrations.AddField(
            model_name='usercurrency',
            name='spend_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercurrency',
            name='user_id',
            field=models.CharField(default='user_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankcurrency',
            name='encrypt_coin_seq',
            field=models.CharField(default='encrypt_coin_seq', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankcurrency',
            name='sign_encrypt_coin_seq',
            field=models.CharField(default='sign_encrypt_coin_seq', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankcurrency',
            name='user_id',
            field=models.CharField(default='user_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='First name', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.CharField(default='Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_num',
            field=models.CharField(default='Identity Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Last_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='09xxxxxxxx', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercurrency',
            name='coin_seq',
            field=models.CharField(default='coin_seq', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercurrency',
            name='denomination',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercurrency',
            name='sign_coin_seq',
            field=models.CharField(default='sign_coin_seq', max_length=100),
        ),
    ]
