# Generated by Django 3.2.16 on 2022-11-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0010_auto_20221121_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_num',
        ),
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.CharField(default='Address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='09xxxxxxxx', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='remaining',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
