# Generated by Django 3.2.16 on 2022-11-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0012_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='access_control_list',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
