# Generated by Django 3.2.16 on 2022-11-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0014_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='currency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_used',
            field=models.IntegerField(),
        ),
    ]
