# Generated by Django 3.2.16 on 2022-11-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0015_auto_20221122_0256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currency',
            new_name='UserBalance',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_used',
            field=models.IntegerField(default=0),
        ),
    ]
