# Generated by Django 3.2.16 on 2022-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0017_alter_userbalance_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('Info', models.CharField(max_length=100)),
                ('R', models.CharField(max_length=100)),
                ('s', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='bankCurrency',
        ),
    ]
