# Generated by Django 3.2.16 on 2022-11-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0018_auto_20221123_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='remaining',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
