# Generated by Django 3.2.16 on 2022-11-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0019_auto_20221123_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='bank_user_payment_id',
        ),
    ]
