# Generated by Django 3.2.16 on 2022-11-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0020_rename_token_user_bank_user_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AESKeyVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='user_id', max_length=100)),
                ('aes_key_verify_ciphertext', models.CharField(default='user_id', max_length=100)),
            ],
        ),
    ]
