# Generated by Django 3.2.16 on 2022-11-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0021_aeskeyverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeskeyverify',
            name='aes_key_verify_ciphertext',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aeskeyverify',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
