# Generated by Django 3.2.16 on 2022-11-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0024_alter_digitalwallet_encrypted_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcurrency',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
