# Generated by Django 3.2.16 on 2022-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0025_alter_usedcurrency_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('used_currency', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
