# Generated by Django 3.2.16 on 2022-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0026_transactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
