# Generated by Django 3.2.16 on 2022-12-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0027_transactionlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
